project_id = "mcomwaelbwvyotvudnzt"

[functions.processar-nota-fiscal]
verify_jwt = true

[functions.receber-pedido-make]
verify_jwt = false

[functions.receber-testemunho-make]
verify_jwt = false

[functions.cadastro-publico]
verify_jwt = false

[functions.checkin-whatsapp-geo]
verify_jwt = false

[functions.checkin-evento]
verify_jwt = false

[functions.verificar-escalas-pendentes]
verify_jwt = false

[functions.analise-sentimento-ia]
verify_jwt = true

[functions.analise-pedido-ia]
verify_jwt = true

[functions.disparar-escala]
verify_jwt = false
