project_id = "mcomwaelbwvyotvudnzt"

[functions.create-first-admin]
enabled = false

[functions.processar-nota-fiscal]
verify_jwt = true

[functions.receber-pedido-make]
verify_jwt = false

[functions.receber-testemunho-make]
verify_jwt = false
